apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.125.200-192.168.125.250  # 你的集群可用外部 IP 范围
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - lb-ip-pool


