---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
---
# OpenLDAP Deployment（不挂卷）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: ghcr.io/wuqiang0720/openldap:latest
        ports:
        - containerPort: 389
        livenessProbe:
          tcpSocket:
            port: 389
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
---
# phpLDAPadmin Deployment（不挂卷）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap-phpadmin
  namespace: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap-phpadmin
  template:
    metadata:
      labels:
        app: openldap-phpadmin
    spec:
      containers:
      - name: phpldapadmin
        image: ghcr.io/wuqiang0720/phpldapadmin:https
        ports:
        - containerPort: 80
        env:
        - name: PHPLDAPADMIN_HTTPS
          value: "false"
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: "openldap"
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
---
# OpenLDAP Service
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
spec:
  type: ClusterIP
  clusterIP: 192.168.1.2   # 手动指定的 ClusterIP（必须在 --service-cluster-ip-range 内）
  selector:
    app: openldap
  ports:
  - port: 389
    targetPort: 389
---
# phpLDAPadmin Service
apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  namespace: openldap
spec:
  type: NodePort
  clusterIP: 192.168.1.3
  selector:
    app: openldap-phpadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081

